#!/bin/sh
####### Initial project run as a development mode #######
set -e
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.5.0
cd /var/www/html \
&& composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.4 . \
&& bin/magento setup:install --base-url="http://192.168.7.121:8989/" --db-host=magentodb --db-name=magentodb --db-user=magento \
--db-password=654321@Bd --admin-firstname=Monowar --admin-lastname=Hossain --admin-email=bdmonowar@gmail.com --admin-user=admin \
--admin-password=admin@321 --language=en_US --currency=BDT --timezone=Asia/Dhaka --use-rewrites=1 --backend-frontname="admin" \
--search-engine=elasticsearch7 --elasticsearch-host="magentoelasticsearch" --elasticsearch-port=9200 \
&& chmod u+x bin/magento && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + \
&& find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + \
&& chown -R www-data. ../html && bin/magento module:disable Magento_TwoFactorAuth
sed -i '4,14 s/^/#/' /usr/local/bin/docker-php-entrypoint
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
exec "$@"

####### Production mode script #######
#set -e
#cd /var/www/html && chmod +x bin/magento && bin/magento setup:upgrade && bin/magento indexer:reindex && bin/magento c:c && bin/magento cache:flush \
#&& chmod +x bin/magento && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + \
#&& find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + && chown -R www-data. . \
#&& bin/magento setup:store-config:set --base-url="http://localhost/"
#if [ "${1#-}" != "$1" ]; then
#	set -- php-fpm "$@"
#fi
#exec "$@"