#!/bin/sh
set -e
cd /var/www/html && chmod +x bin/magento && bin/magento setup:upgrade && bin/magento indexer:reindex && bin/magento c:c && bin/magento cache:flush \
&& chmod +x bin/magento && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + \
&& find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + && chown -R www-data. . \
&& bin/magento setup:store-config:set --base-url="http://192.168.0.152:8989/"
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
exec "$@"

Admin123